# Generated by Django 3.1.5 on 2021-03-23 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.CharField(blank=True, choices=[('Architecture', 'Architecture'), ('Interior', 'Interior')], max_length=20, null=True),
        ),
    ]
