# Generated by Django 3.1.5 on 2021-02-16 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.png', upload_to='teamphotos'),
        ),
    ]
