# Generated by Django 3.1.5 on 2021-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0002_auto_20210216_1320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='photo',
            field=models.ImageField(default='default.jpg', upload_to='teamphotos'),
        ),
    ]
